apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-microservice
spec:
  replicas: 5
  selector:
    matchLabels:
      app: springboot-microservice
  template:
    metadata:
      labels:
        app: springboot-microservice
    spec:
      containers:
        - name: springboot-container
          image: springboot-microservice
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot-microservice
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080